@startuml
start
:query Omega Instance list by serviceName;
repeat
  :get OmegaCallback by Omega instance;
  :OmegaCallback.compensate();
  if (succeed?) then (yes)
    :COMPENSATED;
    stop
  else (no)
    if (CompensateAskFailedException)
      :SUSPENDED;
    elseif (OmegaDisconnectedException)
      :SUSPENDED;
    endif
  endif
repeat while (more data?)
stop
@enduml